// Generated by gencpp from file dm_hw/MotorState.msg
// DO NOT EDIT!


#ifndef DM_HW_MESSAGE_MOTORSTATE_H
#define DM_HW_MESSAGE_MOTORSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace dm_hw
{
template <class ContainerAllocator>
struct MotorState_
{
  typedef MotorState_<ContainerAllocator> Type;

  MotorState_()
    : header()
    , names()
    , position()
    , velocity()
    , effort()
    , cmd_position()
    , cmd_velocity()
    , cmd_effort()
    , kp()
    , kd()  {
    }
  MotorState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , names(_alloc)
    , position(_alloc)
    , velocity(_alloc)
    , effort(_alloc)
    , cmd_position(_alloc)
    , cmd_velocity(_alloc)
    , cmd_effort(_alloc)
    , kp(_alloc)
    , kd(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _names_type;
  _names_type names;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _position_type;
  _position_type position;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _velocity_type;
  _velocity_type velocity;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _effort_type;
  _effort_type effort;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _cmd_position_type;
  _cmd_position_type cmd_position;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _cmd_velocity_type;
  _cmd_velocity_type cmd_velocity;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _cmd_effort_type;
  _cmd_effort_type cmd_effort;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _kp_type;
  _kp_type kp;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _kd_type;
  _kd_type kd;





  typedef boost::shared_ptr< ::dm_hw::MotorState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dm_hw::MotorState_<ContainerAllocator> const> ConstPtr;

}; // struct MotorState_

typedef ::dm_hw::MotorState_<std::allocator<void> > MotorState;

typedef boost::shared_ptr< ::dm_hw::MotorState > MotorStatePtr;
typedef boost::shared_ptr< ::dm_hw::MotorState const> MotorStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dm_hw::MotorState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dm_hw::MotorState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dm_hw::MotorState_<ContainerAllocator1> & lhs, const ::dm_hw::MotorState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.names == rhs.names &&
    lhs.position == rhs.position &&
    lhs.velocity == rhs.velocity &&
    lhs.effort == rhs.effort &&
    lhs.cmd_position == rhs.cmd_position &&
    lhs.cmd_velocity == rhs.cmd_velocity &&
    lhs.cmd_effort == rhs.cmd_effort &&
    lhs.kp == rhs.kp &&
    lhs.kd == rhs.kd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dm_hw::MotorState_<ContainerAllocator1> & lhs, const ::dm_hw::MotorState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dm_hw

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dm_hw::MotorState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dm_hw::MotorState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dm_hw::MotorState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dm_hw::MotorState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dm_hw::MotorState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dm_hw::MotorState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dm_hw::MotorState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4f108578f1cff586bb9978189901903d";
  }

  static const char* value(const ::dm_hw::MotorState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4f108578f1cff586ULL;
  static const uint64_t static_value2 = 0xbb9978189901903dULL;
};

template<class ContainerAllocator>
struct DataType< ::dm_hw::MotorState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dm_hw/MotorState";
  }

  static const char* value(const ::dm_hw::MotorState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dm_hw::MotorState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"# Motor names (corresponds to indices in arrays below)\n"
"string[] names\n"
"\n"
"# Current state values\n"
"float64[] position      # Current position of each motor\n"
"float64[] velocity      # Current velocity of each motor\n"
"float64[] effort        # Current effort/torque of each motor\n"
"\n"
"# Command values\n"
"float64[] cmd_position  # Commanded position of each motor\n"
"float64[] cmd_velocity  # Commanded velocity of each motor\n"
"float64[] cmd_effort    # Commanded effort/torque of each motor\n"
"\n"
"# Control parameters\n"
"float64[] kp            # Proportional gain for each motor\n"
"float64[] kd            # Derivative gain for each motor\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::dm_hw::MotorState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dm_hw::MotorState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.names);
      stream.next(m.position);
      stream.next(m.velocity);
      stream.next(m.effort);
      stream.next(m.cmd_position);
      stream.next(m.cmd_velocity);
      stream.next(m.cmd_effort);
      stream.next(m.kp);
      stream.next(m.kd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dm_hw::MotorState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dm_hw::MotorState_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "names: ";
    if (v.names.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.names.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, true ? std::string() : indent + "    ", v.names[i]);
    }
    if (v.names.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "position: ";
    if (v.position.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.position.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.position[i]);
    }
    if (v.position.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "velocity: ";
    if (v.velocity.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.velocity.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.velocity[i]);
    }
    if (v.velocity.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "effort: ";
    if (v.effort.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.effort.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.effort[i]);
    }
    if (v.effort.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cmd_position: ";
    if (v.cmd_position.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.cmd_position.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.cmd_position[i]);
    }
    if (v.cmd_position.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cmd_velocity: ";
    if (v.cmd_velocity.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.cmd_velocity.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.cmd_velocity[i]);
    }
    if (v.cmd_velocity.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cmd_effort: ";
    if (v.cmd_effort.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.cmd_effort.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.cmd_effort[i]);
    }
    if (v.cmd_effort.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "kp: ";
    if (v.kp.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.kp.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.kp[i]);
    }
    if (v.kp.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "kd: ";
    if (v.kd.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.kd.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.kd[i]);
    }
    if (v.kd.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // DM_HW_MESSAGE_MOTORSTATE_H
