#!/usr/bin/env bash
set -euo pipefail

SCRIPT_TAG="install_opp_camera_udev_rule"

usage() {
  cat <<'EOF'
Usage:
  install_opp_camera_udev_rule.sh [--device /dev/videoN] [--symlink wrist_opp_camera] [--rule-file /etc/udev/rules.d/99-wrist-opp-camera.rules] [--dry-run]

Description:
  Generate and install a persistent udev rule for a USB V4L2 camera.
  The rule creates /dev/<symlink> for the camera's index0 video node.

Examples:
  bash workspaces/scripts/install_opp_camera_udev_rule.sh --device /dev/video18
  bash workspaces/scripts/install_opp_camera_udev_rule.sh --device /dev/video18 --symlink wrist_opp_camera
  bash workspaces/scripts/install_opp_camera_udev_rule.sh --device /dev/video18 --dry-run
EOF
}

die() {
  echo "[${SCRIPT_TAG}] $*" >&2
  exit 1
}

require_cmd() {
  local cmd="$1"
  command -v "${cmd}" >/dev/null 2>&1 || die "Required command not found: ${cmd}"
}

run_as_root() {
  if [[ "$(id -u)" -eq 0 ]]; then
    "$@"
    return
  fi
  if command -v sudo >/dev/null 2>&1; then
    sudo "$@"
    return
  fi
  die "Need root privileges for '$*' (install sudo or run as root)."
}

extract_prop() {
  local key="$1"
  local data="$2"
  awk -F= -v key="${key}" '
    $1 == key { print substr($0, length(key) + 2); found=1; exit }
    END { if (!found) exit 1 }
  ' <<<"${data}"
}

DEVICE="/dev/video0"
SYMLINK="wrist_opp_camera"
RULE_FILE="/etc/udev/rules.d/99-wrist-opp-camera.rules"
DRY_RUN=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --device)
      [[ $# -ge 2 ]] || die "Missing value for --device"
      DEVICE="$2"
      shift 2
      ;;
    --symlink)
      [[ $# -ge 2 ]] || die "Missing value for --symlink"
      SYMLINK="$2"
      shift 2
      ;;
    --rule-file)
      [[ $# -ge 2 ]] || die "Missing value for --rule-file"
      RULE_FILE="$2"
      shift 2
      ;;
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      die "Unknown argument: $1 (use --help)"
      ;;
  esac
done

require_cmd udevadm
require_cmd install

[[ "${DEVICE}" == /dev/* ]] || die "--device must be an absolute /dev path"
[[ "${SYMLINK}" != */* ]] || die "--symlink must be a single device name (no /)"
[[ "${SYMLINK}" =~ ^[A-Za-z0-9._-]+$ ]] || die "--symlink contains invalid characters"

if [[ ! -e "${DEVICE}" ]]; then
  die "Device does not exist: ${DEVICE}"
fi

REAL_DEVICE="$(readlink -f "${DEVICE}" 2>/dev/null || echo "${DEVICE}")"
if [[ ! -c "${REAL_DEVICE}" ]]; then
  die "Not a character device: ${REAL_DEVICE}"
fi

PROPS="$(udevadm info --query=property --name "${REAL_DEVICE}")"
VID="$(extract_prop ID_VENDOR_ID "${PROPS}" || true)"
PID="$(extract_prop ID_MODEL_ID "${PROPS}" || true)"
SERIAL_SHORT="$(extract_prop ID_SERIAL_SHORT "${PROPS}" || true)"
ID_PATH="$(extract_prop ID_PATH "${PROPS}" || true)"

RULE='SUBSYSTEM=="video4linux", KERNEL=="video*", ATTR{index}=="0"'
MATCH_MODE=""

if [[ -n "${VID}" && -n "${PID}" && -n "${SERIAL_SHORT}" ]]; then
  RULE+=", ENV{ID_VENDOR_ID}==\"${VID}\""
  RULE+=", ENV{ID_MODEL_ID}==\"${PID}\""
  RULE+=", ENV{ID_SERIAL_SHORT}==\"${SERIAL_SHORT}\""
  MATCH_MODE="serial"
elif [[ -n "${ID_PATH}" ]]; then
  RULE+=", ENV{ID_PATH}==\"${ID_PATH}\""
  MATCH_MODE="path"
else
  die "Unable to derive stable identifiers for ${REAL_DEVICE}; camera may not expose serial or path metadata."
fi

RULE+=", SYMLINK+=\"${SYMLINK}\""

TMP_RULE="$(mktemp)"
cleanup() {
  rm -f "${TMP_RULE}"
}
trap cleanup EXIT

{
  echo "# Auto-generated by ${SCRIPT_TAG} on $(date -Iseconds)"
  echo "# Source device: ${REAL_DEVICE}"
  echo "# Match mode: ${MATCH_MODE}"
  echo "${RULE}"
} > "${TMP_RULE}"

if [[ "${DRY_RUN}" == "1" ]]; then
  echo "[${SCRIPT_TAG}] Dry-run: generated rule content:"
  cat "${TMP_RULE}"
  exit 0
fi

run_as_root install -D -m 0644 "${TMP_RULE}" "${RULE_FILE}"
run_as_root udevadm control --reload-rules
run_as_root udevadm trigger --subsystem-match=video4linux --action=add

STABLE_DEVICE="/dev/${SYMLINK}"
for _ in $(seq 1 20); do
  if [[ -e "${STABLE_DEVICE}" ]]; then
    break
  fi
  sleep 0.1
done

echo "[${SCRIPT_TAG}] Installed udev rule: ${RULE_FILE}"
echo "[${SCRIPT_TAG}] Match mode: ${MATCH_MODE}"
if [[ -e "${STABLE_DEVICE}" ]]; then
  echo "[${SCRIPT_TAG}] Stable camera path: ${STABLE_DEVICE} -> $(readlink -f "${STABLE_DEVICE}")"
else
  echo "[${SCRIPT_TAG}] Rule installed but ${STABLE_DEVICE} is not visible yet."
  echo "[${SCRIPT_TAG}] Replug camera once, then verify with: ls -l ${STABLE_DEVICE}"
fi

cat <<EOF
[${SCRIPT_TAG}] Launch with stable device:
  opp_camera_usb_port:=
  opp_camera_device:=${STABLE_DEVICE}
EOF
